/**
 * @file    pwm_driver.h
 * @brief   PWM generation on TIM3 channel 1 (PB4) for the brake light.
 *
 * Pulse-width modulation delivers a variable *average* voltage using only a
 * fully-on or fully-off switch. The load sees:
 *
 *      V_average = V_supply * duty_cycle
 *
 * This is the same principle as a buck converter or a motor drive: the switch
 * dissipates almost no power because it is never in its linear region, so
 * efficiency stays high. Controlling a lamp with a resistor would burn the
 * difference as heat; controlling it with PWM does not.
 *
 * Inside the timer, PWM is generated by comparing a free-running counter
 * against a compare register:
 *
 *      counter ──┐   ┌──────┐   ┌──────┐   ┌──
 *         ARR ───┤  ╱│     ╱│  ╱│     ╱│  ╱
 *         CCR ───┼─╱─┼────╱─┼─╱─┼────╱─┼─╱
 *           0 ───┴╱  └───╱  └─╱  └───╱  └╱
 *                 ┌─┐    ┌─┐    ┌─┐    ┌─┐
 *      output ────┘ └────┘ └────┘ └────┘ └──
 *                 <-->  duty = CCR / (ARR+1)
 *
 * The output is high while counter < CCR and low afterwards. Writing a new
 * CCR value changes the duty cycle; the frequency, set by the prescaler and
 * auto-reload register, stays fixed.
 */

#ifndef DRIVERS_PWM_DRIVER_H
#define DRIVERS_PWM_DRIVER_H

#include <stdbool.h>
#include <stdint.h>

/**
 * @brief Configure TIM3 for 1 kHz PWM and start channel 1 at 0% duty.
 *
 * @return true on success, false if the HAL rejected the configuration.
 */
bool PwmDriver_Init(void);

/**
 * @brief Set the brake light duty cycle.
 *
 * @param duty_ticks  0 .. ECU_PWM_DUTY_MAX, where ECU_PWM_DUTY_MAX is 100%.
 *                    Values above the maximum are clamped. Because the timer
 *                    period is exactly 1000 ticks, duty_ticks is also the
 *                    duty cycle in tenths of a percent.
 */
void PwmDriver_SetBrakeDuty(uint16_t duty_ticks);

/**
 * @brief Return the duty cycle currently commanded.
 *
 * @return Last value passed to PwmDriver_SetBrakeDuty(), after clamping.
 */
uint16_t PwmDriver_GetBrakeDuty(void);

#endif /* DRIVERS_PWM_DRIVER_H */
